version: "3"

services:

  nginx:
    # image: nginx:latest
    # image: fholzer/nginx-brotli
    build:
      context: ./nginx
      args:
        - TZ=${TZ}
        - SITE_NAME=${SITE_NAME}
    # container_name: nginx
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443
    volumes:
      # - ./hosts:/etc/nginx/conf.d:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/templates/:/etc/nginx/templates
      - ./www:/var/www/html
      - ./logs/nginx:/var/log/nginx
      - ./logs/php:/var/log/php:ro
      # - ./nginx/ssl:/opt/ssl:ro
      - /etc/localtime:/etc/localtime:ro
    # entrypoint: sh -c "/opt/ssl/ssl.sh"
    links:
      - php
      - db
    restart: unless-stopped
    environment:
      - SITE_NAME=${SITE_NAME}

  php:
    build: ./php
    # container_name: php
    links:
      - db
    volumes:
      - ./www:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ}
    restart: unless-stopped

  # TODO: Вынести в отдельный Dockerfile + создать tmpfs и смортировать её и указать в tmpdir в my.cnf
  db:
    image: mariadb
    # container_name: db
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./logs/mysql:/var/log/mysql
      - ./db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MARIADB_INITDB_SKIP_TZINFO=${MARIADB_INITDB_SKIP_TZINFO}
      - MARIADB_AUTO_UPGRADE=${MARIADB_AUTO_UPGRADE}
    restart: unless-stopped

  # redis:
  #   image: docker.io/bitnami/redis:7.0
  #   environment:
  #     # ALLOW_EMPTY_PASSWORD is recommended only for development.
  #     - ALLOW_EMPTY_PASSWORD=yes
  #     - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
