version: "3"

services:
  nginx:
    build:
      context: ./nginx
      args:
        - TZ=${TZ}
        - SITE_NAME=${SITE_NAME}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 127.0.0.1:80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/templates/:/etc/nginx/templates
      - ./www:/var/www/html
      - ./logs/nginx:/var/log/nginx
      - ./logs/php:/var/log/php:ro
      - /etc/localtime:/etc/localtime:ro
    links:
      - php
      - db
    restart: unless-stopped
    environment:
      - SITE_NAME=${SITE_NAME}

  php:
    build:
      context: ./php
      args:
        - TZ=${TZ}
        - PHP_VERSION=${PHP_VERSION}
    links:
      - db
    volumes:
      - ./www:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ}
    restart: unless-stopped

  db:
    image: mariadb
#    ports:
#      - 127.0.0.1:3306:3306
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./logs/mysql:/var/log/mysql
      - ./db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MARIADB_INITDB_SKIP_TZINFO=${MARIADB_INITDB_SKIP_TZINFO}
      - MARIADB_AUTO_UPGRADE=${MARIADB_AUTO_UPGRADE}
    restart: unless-stopped
